# -*- coding: utf-8 -*-
"""sklearn LogisticRegression Tennis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_X0-MsvgREi7eJTPzMkWclfCEYq_rO0r
"""

import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

url = "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/refs/heads/master/atp_matches_futures_2024.csv"
tennis = pd.read_csv(url, sep = ",")

tennis["surface"] = tennis["surface"].map({"Clay": [0], "Grass": [1], "Hard": [2]})

tennis["rank_difference"] = tennis["loser_rank"] - tennis["winner_rank"]
tennis["target"] = (tennis["rank_difference"] >0).astype(int)

tennis = tennis.dropna(subset = ["winner_rank", "loser_rank", "surface"])

x = tennis[["rank_difference"]]
y = tennis["target"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

model = LogisticRegression()

model.fit(x_train, y_train)

pred = model.predict(x_test)

classification_report(y_test, pred)

confusion_matrix(y_test, pred)

accuracy_score(y_test, pred)

pred

winner = 1
loser = 2
rank_difference = winner - loser
sample = pd.DataFrame({"rank_difference": [rank_difference]})
pred1 = model.predict(sample)[0]
proba = model.predict_proba(sample)[0][1]

pred1

proba

