# -*- coding: utf-8 -*-
"""Sklearn LinearRegression Netflix stockes (PRACTISE)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ym9NvCbyUGv00GdGVMyeNsiqDSbpHd1O
"""

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

url = "https://raw.githubusercontent.com/Sean578-hub/My-datasets/refs/heads/main/Netflix_stock_data.csv"
stock = pd.read_csv(url, sep = ",")

x = stock.drop("Close", axis = 1)
x = stock.drop("Date", axis = 1)
y = stock["Close"]

x_train, x_test, y_trian, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

model = LinearRegression()

model.fit(x_train, y_trian)

pred = model.predict(x_test)
pred

np.sqrt(mean_squared_error(y_test, pred))



