# -*- coding: utf-8 -*-
"""Sklearn LinearRegretion Ethereum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17M6n9-p9qF3rcqrTF77dRoXnM17CRin9
"""

import sklearn
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/Sean578-hub/My-datasets/refs/heads/main/Ethereum%20Usd%20last%205%20Years%20DataSet.csv"
ethirium = pd.read_csv(url, sep = ",")

x = ethirium[["Open", "High", "Low", "Volume"]]
y = ethirium["Close"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 42)

model = LinearRegression()

model.fit(x_train, y_train)

pred = model.predict(x_test)

rsme = np.sqrt(mean_squared_error(y_test, pred))
rsme

plt.figure(figsize = (10, 6))
plt.plot(y_test.values[:50], label = "Actual values")
plt.xlabel("Index")
plt.ylabel("Price")
plt.grid(True)
plt.show()
plt.figure(figsize = (10, 6))
plt.plot(pred[:50], label = "Predicted results")
plt.legend()
plt.xlabel("Index")
plt.ylabel("Price")
plt.grid(True)
plt.show()

yesterday = pd.DataFrame([{"Open": 2972.44, "High": 3081.61, "Low": 2963.35, "Volume": 815550}])
pred_yesterday = model.predict(yesterday)

pred_yesterday

Actual = 3013

july_12 = pd.DataFrame([{"Open": 2971.67, "High": 3018.8, "Low": 2937.62, "Volume": 414190}])
pred_july12 = model.predict(july_12)

pred_july12

Actual = 2942

