# -*- coding: utf-8 -*-
"""Sklearn XGBClassifier Heart Disease

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16v6RqFlpng9WE0UL-msX8fY49RquRBAp
"""

import sklearn
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

url = "https://raw.githubusercontent.com/Sean578-hub/My-datasets/refs/heads/main/heart_cleveland_upload.csv"
heart = pd.read_csv(url, sep = ",")

x = heart.drop("condition", axis = 1)
y = heart["condition"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

model = XGBClassifier(use_label_encoder = False, eval_metric = "logloss")

model.fit(x_train, y_train)

pred = model.predict(x_test)
pred

accuracy_score(y_test, pred)

confusion_matrix(y_test, pred)

classification_report(y_test, pred)

