# -*- coding: utf-8 -*-
"""Sklearn LogisticRegression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkIZC3dTBm3PvJIdAA69wIyAWoxgoXwT
"""

import sklearn
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    'Age': [25, 30, 35, 40, 45, 28, 32, 38, 50, 29, 36, 41, 55, 27, 33],
    'YearsAtCompany': [1, 3, 5, 10, 15, 2, 4, 6, 20, 1, 5, 12, 25, 1, 3],
    'Salary': [30000, 35000, 40000, 50000, 60000, 32000, 37000, 42000, 70000, 31000, 41000, 55000, 80000, 30000, 36000],
    'LeftCompany': [1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
}

df = pd.DataFrame(data)

x = df[["Age", "YearsAtCompany", "Salary"]]
y = df[["LeftCompany"]]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

model = LogisticRegression()

model.fit(x_train, y_train)

pred = model.predict(x_test)
pred

classification_report(y_test, pred)

confusion_matrix(y_test, pred)

new_employee = pd.DataFrame({"Age": [34], "YearsAtCompany": [2], "Salary": [37000]})

pred2 = model.predict(new_employee)[0]
proba = model.predict_proba(new_employee)[0][1]

pred2

proba

