# -*- coding: utf-8 -*-
"""Sklearn wine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tApsyI7jg56qzzGpMG__ypUdE_oHym90
"""

import sklearn
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

wine = load_wine()

x = wine.data
y = wine.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

model = KNeighborsClassifier(n_neighbors = 3)

model.fit(x_train, y_train)

pre = model.predict(x_test)

accuracy_score(y_test, pre)

