# -*- coding: utf-8 -*-
"""Sklearn LogisticRegression Weather Detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DaSfyboCXxtAhGkEKK7JkdJxtIqufrIZ
"""

import sklearn
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

url = "https://raw.githubusercontent.com/Sean578-hub/My-datasets/refs/heads/main/weatherAUS.csv"
raw_df = pd.read_csv(url, sep = ",")

raw_df.head()

raw_df = raw_df[["MinTemp", "MaxTemp", "Rainfall", "Humidity9am", "Humidity3pm", "RainToday", "RainTomorrow"]]
raw_df = raw_df.dropna()

raw_df["RainToday"] = raw_df["RainToday"].map({'No': 0, 'Yes': 1})
raw_df["RainTomorrow"] = raw_df["RainTomorrow"].map({'No': 0, 'Yes': 1})

raw_df["RainToday"]

x = raw_df.drop("RainTomorrow", axis = 1)
y = raw_df["RainTomorrow"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

model = LogisticRegression(max_iter = 1000)

model.fit(x_train, y_train)

pred = model.predict(x_test)
pred

proba = model.predict_proba(x_test)[:, 1]
proba

classification_report(y_test, pred)

confusion_matrix(y_test, pred)

sample = pd.DataFrame({"MinTemp": [17], "MaxTemp": [28], "Rainfall": [100.0], "Humidity9am": [90], "Humidity3pm": [80], "RainToday": [1]})
pred1 = model.predict(sample)[0]
prob1 = model.predict_proba(sample)[0][1]

pred1

prob1

