# -*- coding: utf-8 -*-
"""Sklearn RandomForestClassifier Diabetes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyAg34CfRR9OgFupOdfhvTjmZrKxp0NC
"""

import sklearn
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

url = "https://raw.githubusercontent.com/Sean578-hub/My-datasets/refs/heads/main/diabetes.csv"
Diabetes = pd.read_csv(url, sep = ",")

x = Diabetes.drop("Outcome", axis = 1)
y = Diabetes["Outcome"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

model = RandomForestClassifier(n_estimators = 100, random_state = 42)

model.fit(x_train, y_train)

pred = model.predict(x_test)
pred

accuracy_score(y_test, pred)

classification_report(y_test, pred)

