# -*- coding: utf-8 -*-
"""Sklearn breast cancer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DXZ-WnHRuNRZa6MYW0UApiMjokJbm3J
"""

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score

cancer = load_breast_cancer()

x = cancer.data
y = cancer.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

model = KNeighborsClassifier()

model.fit(x_train, y_train)

pred = model.predict(x_test)

model2 = DecisionTreeClassifier()

model2.fit(x_train, y_train)

pred2 = model2.predict(x_test)

accuracy_score(y_test, pred)

accuracy_score(y_test, pred2)

