# -*- coding: utf-8 -*-
"""Sklearn LinearRegression Salary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA2n2bTh4q73e7Dn8rkPHLeXf7qXrw4K
"""

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/Sean578-hub/Dataset/refs/heads/main/Salary_dataset.csv"
data = pd.read_csv(url, sep = ",")

x = data[["YearsExperience"]]
y = data[["Salary"]]

model = LinearRegression()

model.fit(x, y)

pred = model.predict(x)

rmse = np.sqrt(mean_squared_error(y, pred))
rmse

plt.figure(figsize = (10, 6))
plt.scatter(data[["YearsExperience"]], data[["Salary"]])
plt.xlabel("Salray")
plt.ylabel("YearsExperience")
plt.show()

