# -*- coding: utf-8 -*-
"""Sklearn LinearRegression Netflix stockes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-vtsc7rwYclIltsm4sGZAilowMZGeWl
"""

import sklearn
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

url = "https://raw.githubusercontent.com/Sean578-hub/My-datasets/refs/heads/main/Netflix_stock_data.csv"
stock = pd.read_csv(url, sep = ",")

x = stock[["Open", "High", "Low", "Volume"]]
y = stock["Close"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

model = LinearRegression()

model.fit(x_train, y_train)

pred = model.predict(x_test)

np.sqrt(mean_squared_error(y_test, pred))

pred

plt.figure(figsize = (10, 6))
plt.plot(y_test.values[:50], label = "Actioal Resolts")
plt.xlabel("Index")
plt.ylabel("Price")
plt.grid(True)
plt.show()
plt.plot(pred[:50], label = "Prediction")
plt.legend()
plt.xlabel("Index")
plt.ylabel("Price")
plt.grid(True)
plt.show()

yesterday = pd.DataFrame([{"Open": 1244.91, "High": 1270.49, "Low": 1240, "Volume": 2781048}])

pred_close_yesterday = model.predict(yesterday)[0]

pred_close_yesterday

actual_result = 1261.95

july_11 = pd.DataFrame([{"Open": 1259.79, "High": 1261, "Low": 1231.3, "Volume": 3957150}])

pred_close_july11 = model.predict(july_11)
pred_close_july11

accutual = 1254.5

july_10 = pd.DataFrame([{"Open": 1285.5, "High": 1289.6, "Low": 1246.01, "Volume": 4236494}])

pred_close_july10 = model.predict(july_10)
pred_close_july10

accutual1 = 1258.49

