# -*- coding: utf-8 -*-
"""Sklearn LinearRegression ACME Inshurence

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qonZB-NulbP99B9CDzN2Ye2L6Tkutsbb
"""

import sklearn
from sklearn.linear_model import LinearRegression
import pandas as pd
from urllib.request import urlretrieve
from sklearn.metrics import mean_squared_error
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/JovianML/opendatasets/master/data/medical-charges.csv"
host = pd.read_csv(url, sep = ",")

urlretrieve(url, "medical.csv")

host["sex"] = host["sex"].map({"male": 0, "female": 1})
host["region"] = host["region"].map({"southwest": 0, "southeast": 1, "northwest": 2, "northeast": 3})
host["smoker"] = host["smoker"].map({"yes": 1, "no": 0})

x = host[["age", "sex", "bmi", "children", "smoker", "region"]]
y = host["charges"]

model = LinearRegression()

model.fit(x, y)

y_pred = model.predict(x)
y_pred

rmse = np.sqrt(mean_squared_error(y, y_pred))
rmse

coef_df = pd.DataFrame({"Fearutre": x.columns, "Weight(Coefficient)": model.coef_})
coef_df

plt.figure(figsize = (8,6))
sns.scatterplot(x = y, y = y_pred, alpha = 0.6)
plt.plot([y.min(), y.max()], [y.min(), y.max()], "r--")
plt.xlabel("Actual Charges")
plt.ylabel("Predicted Charges")
plt.ylabel("Predicted Charges")
plt.title("Actual vs Predicted Medical Charges")
plt.grid(True)
plt.show()

new_client = pd.DataFrame({"age": [35], "sex": [1], "bmi": [28.0], "children": [2], "smoker": [0], "region": [2]})
model.predict(new_client)

new_client2 = pd.DataFrame({"age": [50], "sex": [0], "bmi": [27.5], "children": [0], "smoker": [0], "region": [0]})
model.predict(new_client2)

new_client2 = pd.DataFrame({"age": [14], "sex": [0], "bmi": [23.7], "children": [0], "smoker": [0], "region": [0]})
model.predict(new_client2)

