# -*- coding: utf-8 -*-
"""Sklearn digits KNeighborsClassifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbhECrwUFVgsQqdbUpAJ_0vlJTkAH9hx
"""

import sklearn
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

dig = load_digits()

x = dig.data
y = dig.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

model = KNeighborsClassifier(n_neighbors = 3)

model.fit(x_train, y_train)

pred = model.predict(x_test)

accuracy_score(y_test, pred)

plt.gray()
plt.matshow(dig.images[0])
plt.show()

