# -*- coding: utf-8 -*-
"""Sklearn RandomForestClassifier Maternal Health and High-Risk Pregnancy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANdCyLlpIrFGyGC2_ehXbVtOXBXZNGRC
"""

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/Sean578-hub/My-datasets/refs/heads/main/Maternal%20Health%20and%20High-Risk%20Pregnancy%20Dataset.csv"
health = pd.read_csv(url, sep = ",")

le = LabelEncoder()
health["Risk Level"] = le.fit_transform(health["Risk Level"])
x = health.drop("Risk Level", axis = 1)
y = health["Risk Level"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

model = RandomForestClassifier(n_estimators = 100, random_state = 42)

model.fit(x_train, y_train)

pred = model.predict(x_test)
pred

accuracy_score(y_test, pred)

confusion_matrix(y_test, pred)

classification_report(y_test, pred)

