# -*- coding: utf-8 -*-
"""Sklearn Iris

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-a21lqsoS2TVKebnWIQx7qlKESKvTSc
"""

import sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt

iris = load_iris()

x = iris.data
y = iris.target

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

model = DecisionTreeClassifier()

model.fit(x_train, y_train)

pred = model.predict(x_test)

accuracy_score(y_test, pred)

example = [[5.1, 3.5, 1.4, 0.2]]
prediction = model.predict(example)
iris.target_names[prediction[0]]

clas = classification_report(y_test, pred, target_names = iris.target_names)
clas

y_test

pred

plt.figure(figsize = (10,6))
plt.scatter(iris.data[:, 0], iris.data[:, 1], c = iris.target)
plt.show()

